language: node_js
node_js:
- 7
branches:
  only:
  - master
install:
- npm install
script:
- npm run build
addons:
  code_climate:
    repo_token: "$CODE_CLIMATE"
#deploy:
#  skip_cleanup: true
#  provider: heroku
#  api_key:
#    secure: "$HEROKU_KEY"
#  app: "$HEROKU_APP"
